services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    expose: [ "5173" ]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      target: dev
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/src:/app/src
      - /app/node_modules

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
      - scalar
    ports: [ "80:80" ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
